module.exports =`
id:String,
Name:String,
Date_of_Birth: String,
Email:String,
Telephone_1: String,
Telephone_2:String,
Address:String,
Member:String,
Gender:String,
Marital_Status: String,
Occupation:String,
Place_of_Work:String,
Course:String,
Next_of_kin:String,
Membership_Status:String,
Dept:String,
HFellowship:String,
`
